name = "cloudflare-docker-proxy"
compatibility_date = "2025-01-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "iflyelf.com"
CUSTOM_DOMAIN = "xiaonuo.in"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
   { pattern = "docker.iflyelf.com", custom_domain = true },
   { pattern = "quay.iflyelf.com", custom_domain = true },
   { pattern = "gcr.iflyelf.com", custom_domain = true },
   { pattern = "k8s-gcr.iflyelf.com", custom_domain = true },
   { pattern = "k8s.iflyelf.com", custom_domain = true },
   { pattern = "ghcr.iflyelf.com", custom_domain = true },
   { pattern = "cloudsmith.iflyelf.com", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
route = { pattern = "docker-staging.iflyelf.com", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
